main: typeobject.c nullobject.c trueobject.c falseobject.c \
	boolobject.c numobject.c stringobject.c arrayobject.c jsonobject.c JSON.h test.c
	clang typeobject.c nullobject.c trueobject.c falseobject.c \
		boolobject.c numobject.c stringobject.c arrayobject.c jsonobject.c test.c -Wall -g -o main

make clean:
	rm main
